version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres:0.0.10
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - ./database/database.env
    ports:
      - "5432:5432"